name: Repo Settings

on:
  push:
    paths:
      - .github/settings.yml
  workflow_dispatch:

jobs:
  apply:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Apply repository settings
        uses: probot/settings@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
